[package]
name = "forest_hills_departure"
version = "0.1.0"
authors = ["Rory Coffey <coffeyrt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sh1106 = "0.3.3"
embedded-graphics = "0.6.2"
ssd1306 = "0.4.0"

[dependencies.rppal]
version = "0.11.3"
features = ["hal-unproven"]
